import { ITEM_SPRITES } from '../../itemSprites.ts';

const S = (key: string): string => {
  const v = ITEM_SPRITES[key];
  if (v === undefined) throw new Error(`Missing item sprite: ${key}`);
  return v;
};

export const iron_dagger = S('iron_dagger');
export const rusty_sword = S('rusty_sword');
export const oak_staff = S('oak_staff');
export const mace = S('mace');
export const leather = S('leather');
export const cloth_robe = S('cloth_robe');
export const chain_shirt = S('chain_shirt');
export const third_bell = S('third_bell');
export const rumor_map = S('rumor_map');
export const frost_wyrm_scale = S('frost_wyrm_scale');
export const potion_hp = S('potion_hp');
export const potion_mana = S('potion_mana');
export const potion_stress = S('potion_stress');
export const morvayn_heart_shard = S('morvayn_heart_shard');
export const short_bow = S('short_bow');
export const hunter_robe = S('hunter_robe');
export const leather_quiver = S('leather_quiver');
export const depths_chart = S('depths_chart');
export const frost_pass_map = S('frost_pass_map');
export const fractured_nave_map = S('fractured_nave_map');
export const fallen_god_amulet = S('fallen_god_amulet');
export const magma_ward_amulet = S('magma_ward_amulet');
export const act6_fracture_iron = S('act6_fracture_iron');
export const act6_void_slag = S('act6_void_slag');
export const ash_veil = S('ash_veil');
export const cult_sickle = S('cult_sickle');
export const wind_step_charm = S('wind_step_charm');
export const frost_needle = S('frost_needle');
export const rime_cloak = S('rime_cloak');
export const void_glass_shard = S('void_glass_shard');
export const slag_cleaver = S('slag_cleaver');
export const ember_ring = S('ember_ring');
export const dimensional_ward_plate = S('dimensional_ward_plate');
